### ISSUE TITLE
twitch-title.py causing threading.py errors

### ISSUE THREAD

**Issue by Fironet** [Poorchop/hexchat-scripts#8]
Just installed twitch-title.py and noticed it's producing errors in other networks. Example:

```
Exception in thread Thread-1:
 Traceback (most recent call last):
   File "C:\Python34\Lib\threading.py", line 920, in _bootstrap_inner
     self.run()
   File "C:\Python34\Lib\threading.py", line 1186, in run
     self.function(*self.args, **self.kwargs)
   File "<string>", line 93, in get_current_status
   File "C:\Python34\Lib\threading.py", line 1057, in join
     raise RuntimeError("cannot join current thread")
 RuntimeError: cannot join current thread
```

Not sure what the issue is, but since it's an excellent script that I'd like to continue using thought I'd submit the issue here.

**Comment by Poorchop** [comment]
Thanks for reporting the issue and for liking the script. It's currently in a somewhat messy state and it isn't thread-safe, which is in itself a big issue. I'm gonna be pretty busy for a decent while so I don't know when I'll be able to address this, but I'll keep this issue in mind and get it eventually.
